image: anucecsit/gitlab-pages:1.0.1

page-deploy:
  tags:
  - Pages
  stage: deploy
  script:
    - bundle install
    - jekyll build -d /srv/gitlab-ce-pages/staging/$CI_BUILD_ID/$CI_BUILD_REF_NAME/$CI_PROJECT_PATH
