# Jekyll (https://jekyllrb.com/) uses the information in this file to
# figure out how to generate your website

# for more info on these configuration variables (and more) see
# https://jekyllrb.com/docs/configuration/

# this is a YAML file - for more info on YAML syntax then Ansible's docs have a
# decent explanation: https://docs.ansible.com/ansible/latest/YAMLSyntax.html

#############
# Site Info #
#############

title: Laptop Ensemble
short_title: COMP2710/COMP6470

description: Homepage of the ANU Laptop Ensemble
url: https://cs.anu.edu.au
date_format: "%b %-d, %Y"
# sub-path of your site (/courses/COMPXXXX)
baseurl: "/courses/comp2710-lens"

theme: jekyll-theme-anu

collections:
  workshops:
    output: true
    permalink: /workshops/:path/
  deliverables:
    output: true
    permalink: /deliverables/:path/
  resources:
    output: true
    permalink: /resources/:path/

menu:
  - name: Workshops
    page: _workshops/index.md
  - name: Deliverables
    page: _deliverables/index.md
  - name: Resources
    page: _resources/index.md

# default layouts for different pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _lectures
    values:
      layout: reveal

# the default reveal theme used by the revealify plugin
revealify:
  theme: assets/reveal.js/anu.scss

## moar Jekyll config
markdown: kramdown
kramdown:
  toc_levels: "2,3"
sass:
  style: compressed
