# Jekyll (https://jekyllrb.com/) uses the information in this file to
# figure out how to generate your website

# for more info on these configuration variables (and more) see
# https://jekyllrb.com/docs/configuration/

# this is a YAML file - for more info on YAML syntax then Ansible's docs have a
# decent explanation: https://docs.ansible.com/ansible/latest/YAMLSyntax.html

#############
# Site Info #
#############

title: Laptop Ensemble
short_title: COMP3710/COMP6470
subbrand: ANU School of Computing

description: Laptop Ensemble - a course in sound and music computing
url: https://comp.anu.edu.au
date_format: "%b %-d, %Y"
permalink: pretty
# sub-path of your site (/courses/COMPXXXX)
baseurl: "/courses/laptop-ensemble"

theme: jekyll-theme-anu

contacts:
  responsible_officer:
    name: School Director
    email: director.comp@anu.edu.au
  page_contact:
    name: Charles Martin
    email: charles.martin@anu.edu.au

collections:
  lectures:
    output: true
    permalink: /lectures/:path/
  workshops:
    output: true
    permalink: /workshops/:path/
  assessments:
    output: true
    permalink: /assessments/:path/
  resources:
    output: true
    permalink: /resources/:path/

menu:
  - name: Lectures
    page: _lectures/index.md
  - name: Workshops
    page: _workshops/index.md
  - name: Assessments
    page: _assessments/index.md
  - name: Resources
    page: _resources/index.md
  - name: Policies
    page: 01-policies.md
  - name: Outline
    page: 02-outline.md


# default layouts for different pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
      show_anchor_headings: true
      image: assets/photos/2019-rehearsal-weitong.jpg
      image-tint: "medium"
  -
    scope:
      path: _lectures
    values:
      layout: reveal2300
      theme: assets/revealthemes/charles1720-dark.scss
      no_title_slide: true

# the default reveal theme used by the revealify plugin
revealify:
  theme: assets/revealthemes/charles1720-dark.scss



# show CC license info in footer
cc_license: true

## moar Jekyll config
markdown: kramdown
kramdown:
  toc_levels: "2,3"
sass:
  style: compressed

# TODO need to fix the errors which come up, and then use this
# jekyll_proofer: error
