# Jekyll (http://jekyllrb.com/) uses the information in this file to
# figure out how to generate your website

# for more info on these configuration variables (and more) see
# https://jekyllrb.com/docs/configuration/

# this is a YAML file - for more info on YAML syntax then Ansible's docs have a
# decent explanation: http://docs.ansible.com/ansible/latest/YAMLSyntax.html

#############
# Site Info #
#############

# site name (in words, e.g. the full course name)
title: Long Title

# short site name (e.g. COMPXXXX)
short_title: Short Title

# sub-path of your site (/courses/COMPXXXX)
baseurl: ""

# the base hostname & protocol for your site (generally leave as-is)
url: ""

# your name and email in here
page_contact: Lecturer Name
page_contact_email: lecturer.name@anu.edu.au

# These are for the standard ANU Footer
responsible_officer: Head of School
responsible_officer_email: head.cs@cecs.anu.edu.au

##################
# build settings #
##################

# files/folders to exclude from the build process
exclude:
  - README.md
  - Gemfile

# which markdown processor and syntax highlighter to use
markdown: kramdown
highlighter: highlight.js

theme: jekyll-theme-anu-cecs

assets:
  sources:
    - _assets/
  assets:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"

sass:
  style: compressed

# number of news items to show in the menu on the homepage
newscount: 3

# default layouts for different pages
defaults: 
  - 
    scope: 
      path: ""
    values: 
      layout: page
  - 
    scope: 
      path: _posts
    values: 
      categories: news
      show_date: true
      show_time: true

permalink: /:categories/:year/:month/:day/:title/

navbar: true
globalmenu: false
gitlab_auth: false
search: true
future: true
breadcrumbs: true
style: cecs
# piwik_siteid: x
tablesorter: .tablesorter
charts: true

# collections (set navbar: true to add a tab in the navbar)
collections:
  lectures:
    navbar: true
    output: true
    display-order: 1
    permalink: /lectures/:path/
  labs:
    navbar: true
    output: true
    display-order: 2
    permalink: /labs/:path/
  deliverables:
    navbar: true
    output: true
    display-order: 3
    permalink: /deliverables/:path/

# populate the menu with links to related sites
related_sites:
